<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BCA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script type="application/javascript" src="/js/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
<div class="page-wrap">
    <?php  $this->partial('layouts/header');
     echo $this->getContent();
    $this->partial('layouts/footer'); ?>
</div>


</html>