<html>
<head>
<title>{% block title %}{% endblock %}</title>
{% block styles %}
<link rel="stylesheet" href="/css/style.css" />
{% endblock %}
{% block script %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="/js/main_script.js"></script>
{% endblock %}
</head>
<body>
{% block menu %}
{{ partial("layouts/menu") }}
{% endblock %}
<section class="page-wrap">
{{ partial("layouts/header")}}
<main id="main">
{% block body %}
{% endblock %}
</main>
{% block footer %}
{{ partial("layouts/footer")}}
{% endblock%}
</section>
{% block side %}
<div class="alert-wrap">
    <div class="alert-substrate"></div>
    <div class="alert-box"></div>
</div>
{% endblock %}
</body>
</html>