<main id="main">
    <!-- ********** log-in start popup *********** -->
    <section class="login-wrap">
        <!-- block background image -->
        <div class="top-img-bg"></div>
        <!-- login popup -->
        <div class="login-popup">
            <a href="#" class="without-account">Don't have an account?</a>
            <div class="login-form-wrap">
                <form action="/login/start" method="post">
                    <label for="log" class="label-for"></label>
                    <input id="log" name="email" type="text" placeholder="Login...">
                    <div class="clear"></div> <!-- separator -->
                    <label for="pass" class="label-pass"></label>
                    <input id="pass" name="password" type="password" placeholder="Password...">
                    <a href="#" class="forgot">Forgot Username/Password?</a>
                    <input type="submit" id="login-send" class="submit-button" value="Login">
                </form>
            </div>
        </div>
    </section>
    <!-- ***************************************** -->
</main>